### ISSUE TITLE
Federate with Jami and Tox

### ISSUE THREAD

**Issue by ghost** [peer-calls/peer-calls#104]
It would be great to have the possibility for `peer-calls` users to interact with a user that uses Jami or Tox. What's the point of having so many different, non-federated apps that do the same thing? Who benefits from this redundancy? I believe no one..

**Comment by mxvin** [comment]
I think this kind of issue is not a bug. 
And, that kind of integration kinda impossible because each app is build on different ecosystem, even technology used on that product is different. Jami using SIP with their own "OpenDHT" so it's P2P. Tox I believe also using similar approach, but not using SIP (correct me if I'm wrong)
peer-calls is based on webrtc, it's P2P but still need server to run on. So... yeah

**Comment by jeremija** [comment]
The bug probably got added from the issue template. Yeah, WebRTC is complicated enough on its own. After the SFU-related bugs are fixed, the next steps would be to:

1. Add multi-node SFU support, so that peers connected to different instances of Peer Calls could communicate. This would require these instances to know about each other.

2. Add subscribe/unsubscribe support for specific tracks. Right now the SFU will send all tracks to all peers, which is taxing on the server.

Each of these will take a large chunk of my time and I don't think I have the bandwidth to handle any kind of federation at this point. There could potentially be an option to add federation to connect instances of Peer Calls managed by different people/organizations. Although allowing federation will most likely raise privacy and security issues.

**Comment by DontUseGithub** [comment]
> Although allowing federation will most likely raise privacy issues

Are you implying that all decentralized networks have privacy issue?

**Comment by jeremija** [comment]
No, but when it comes to video/audio streams of _private_ calls, people could be more sensitive about. I'm talking about traffic going through 3rd party SFUs, this is at least until insertable streams are supported in all major browsers.

**Comment by jeremija** [comment]
Closing this issue because federation is not within the scope of this project at the moment.

There is an WIP PR https://github.com/peer-calls/peer-calls/pull/132 that will eventually add suppors for multiple (Peer Calls) SFU nodes, but that's about it.
