### ISSUE TITLE
Multipoint Conferencing Unit (MCU) Setup in network type

### ISSUE THREAD

**Issue by dhruvil2111** [peer-calls/peer-calls#109]
has anyone tried setting up mcu with peer-calls and also anyone solved sfu connectivity issue?
I want to make video conferencing for more than 10 people and I did some research and I find MCU more stable can anyone help me?

**Comment by jeremija** [comment]
Hello, the SFU is currently on `master`, but the master branch is in alpha state until the bugs like these are resolved. I have a potential fix for these issues, but they use unmerged patches to github.com/pion/webrtc so I'm waiting for them to be merged first.

The MCU uses a lot more server side computing power since the server needs to do the transcoding and I don't have the resources to support this at the time.

**Comment by dhruvil2111** [comment]
> Hello, the SFU is currently on `master`, but the master branch is in alpha state until the bugs like these are resolved. I have a potential fix for these issues, but they use unmerged patches to github.com/pion/webrtc so I'm waiting for them to be merged first.
> 
> The MCU uses a lot more server side computing power since the server needs to do the transcoding and I don't have the resources to support this at the time.

Thanks :)

**Comment by jeremija** [comment]
No problem. If you like, I can let you know when I push the SFU fixes? It would be great if you could help me test it!

**Comment by dhruvil2111** [comment]
Sureee Let me know I can test it and thanks alot
