### ISSUE TITLE
error codec

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#121]
error in console when I connect to new partner

https://github.com/peer-calls/peer-calls/blob/1ca84bfe53ad7ec1c304cfe53c07241fa552a28a/src/client/codec/index.ts#L312

![Ekran Resmi 2020-05-15 22 16 37](https://user-images.githubusercontent.com/7665820/82088050-c5561e80-96f9-11ea-9667-51d2b9000f79.png)

**Comment by jeremija** [comment]
@ahmetozalp can you reproduce this on https://peercalls.com ?

**Comment by ahmetozalp** [comment]
there is no error there I've been copied codec for v3.

**Comment by ahmetozalp** [comment]
It is important for me to do this. Can you tell me what I have to do?

**Comment by jeremija** [comment]
@ahmetozalp I do not understand how do you expect me to help here? If you cannot reproduce this bug on peercalls.com, or on a local **unmodified** instance of Peer Calls, then there's no issue to fix.

It looks like your sender is not encoding messages into chunks like it should be:

https://github.com/peer-calls/peer-calls/blob/f553d3fd1f52eb10d55e37209a480a5a3cfaf0e9/src/client/messaging.ts#L41-L44

Most likely because you did not include the messaging middleware in redux configuration:

https://github.com/peer-calls/peer-calls/blob/febbca01090e9a91ce33ce6ae96c6d894963c8b0/src/client/middlewares.ts#L10

I do not know what your codebase looks like and I don't think there's any more advice I can give you here. Good luck with your project!

**Comment by ahmetozalp** [comment]
There is no problem in messaging when this other spouse is connected to the channel gives this warning.
