### ISSUE TITLE
Cannot connect within local network

### ISSUE THREAD

**Issue by vpanichkin** [peer-calls/peer-calls#137]
**Describe the bug**

```
2020/07/22 12:48:54 http: TLS handshake error from 192.168.0.136:40018: remote error: tls: unknown certificate
```

**Steps To Reproduce**

1. Create certificate 
```
openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
  -keyout key.key -out cert.crt \
  -subj "/C=US/ST=CA/L=Irvine/O=Acme Inc./CN=localhost" \
  -reqexts v3_req -reqexts SAN -extensions SAN \
  -config \
  <(echo -e '
    [req]\n
    distinguished_name=req_distinguished_name\n
    [req_distinguished_name]\n
    [SAN]\n
    subjectKeyIdentifier=hash\n
    authorityKeyIdentifier=keyid:always,issuer:always\n
    basicConstraints=CA:TRUE\n
    subjectAltName=IP:192.168.0.136
  ')

```

2. Run server with the correct certificate pathes :
```
		TLSCertFile: "./config/cert.crt",
		TLSKeyFile:  "./config/key.key",
```
6. Access `https://192.168.0.136:3000` from other device

**Current behaviour**
White screen, the request fails with timeout

**Expected behavior**
The site should load.

**Desktop (please complete the following information):**
 - OS:      Ubuntu
 - Browser  Chrome
 - Version  84.0.4147.89

**Desktop (please complete the following information):**
 - Device:  Windows
 - OS:      Firefox
 - Browser: 78.0.2

UPD 1: Deployed from windows machine the server - everything works fine. If I find a real problem - I will text here

**Comment by vpanichkin** [comment]
Windows: works
Ubuntu+docker: works
Clean Ubuntu: doesn't work

**Comment by jeremija** [comment]
Does it work with pregenerated example certificates in `config/` folder?

**Comment by vpanichkin** [comment]
No, HTTPS connection doesn't work either on Ubuntu

**Comment by jeremija** [comment]
I'll try to test it on my Linux machine. Until I do, what kind of error do you get in the browser?

**Comment by jeremija** [comment]
If you're getting a warning like the one below:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/1489493/89105247-cefd4180-d41f-11ea-9120-afff66e79606.png">

this is expected with self-signed certificate. You need to create an exception by clicking on `Advanced` and then on `Proceed to ... (unsafe)`; only then you'll be able to access the webpage. See the screenshot below:

![image](https://user-images.githubusercontent.com/1489493/89105281-11bf1980-d420-11ea-8693-6f3dc1b784b7.png)

I'm closing this issue since there's nothing that can or should be done to get around this. This is TLS certificate validation working as expected. The only thing you can do is to trust this certificate by adding it to the CA store of your browser or operating system.

**Comment by vpanichkin** [comment]
I found a problem. The port was not exposed even inside local network.

This post helps me: https://askubuntu.com/a/1211681
