### ISSUE TITLE
Implementation for native platforms

### ISSUE THREAD

**Issue by chrismgonzalez** [peer-calls/peer-calls#158]
Hello @jeremija,

I am looking to get your thoughts on an implementation for Peer-Calls in native environments such as iOS, Android OS, and Windows desktop.  

Do you think this is possible without developing a custom SDK.  Peer-Calls suits the project I am working on perfectly, we just need to problem solve a mobile implementation that doesn't use a browser.

Thanks in advance for your thoughts on this.

**Comment by jeremija** [comment]
I'm not sure how well supported or similar to browser WebRTC is in React Native, but I assume it would be a good fit because a lot of the client side logic could be reused from existing code.

If you're interested in a more modular SFU with support for native applications in mind, you might want to check out [`pion/ion`](https://github.com/pion/ion/).

**Comment by chrismgonzalez** [comment]
Alright, hopefully we will have some success with something like that.
