### ISSUE TITLE
Nginx subfolder install and proxy configuration

### ISSUE THREAD

**Issue by emannuell** [peer-calls/peer-calls#177]
Hello, first of all i would like thank you for share that work! I really appreciate.
Im running on VM (micro) at GCP with Nginx. At first time running on root from domain works great. But i would like run peer-calls inside a subdirectory to have my website (blog) at front.

**Nginx website (sites-avaliable) configuration:**
location /try {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_pass http://localhost:3000/;
}

**Enviroment variable PEERCALLS_BASE_URL:**
`export PEERCALLS_BASE_URL='/try/'`

**Chrome Console error:**
GET https://mywebsite.com/static/style.css?v0.0.0 net::ERR_ABORTED 404 (Not Found) try:23 
GET https://mywebsite.com/res/peer-calls.svg 404 (Not Found) manifest.json:1 
GET https://mywebsite.com/manifest.json 404 (Not Found)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

**I tryed to build with:**
`npm run build -c /var/www/mywebsite.com/peer-calls/server/config.yml --prod`
**config.yml file:**

base_url: '/try'
bind_host: 'localhost'
bind_port: 3000
ice_servers:
 - urls:
   - 'stun:stun.l.google.com:19302'
- urls:
  - 'stun:global.stun.twilio.com:3478?transport=udp'
store:
  type: memory
network:
  type: mesh
prometheus:
  access_token: "mytoken"

**Error:**

![image](https://user-images.githubusercontent.com/10981452/102388854-16d8cb80-3fb1-11eb-8da8-42aee9720a77.png)

Apparently the application searches for files in the wrong location, disregarding the current root url.
Where can I configure to make a new build considering the work directory?

Thank you

**Comment by jeremija** [comment]
Hi, the `npm run build` command only builds the JavaScript and CSS resources and is not supposed to accept any config files. The `-c /path/to/config.yaml` CLI argument should be provided to the binary that you can either build manually or download from the releases section.

You can also pass the argument to `go run` locally, using either `go run main.go -c <config>` or `npm run start:server -- -c <config>`. Just make sure to execute `npm run build` before so that the JavaScript and CSS resources are built.
