### ISSUE TITLE
[QUESTION] - I cannot connect with multiple user when cloned and built locally

### ISSUE THREAD

**Issue by sujit-baniya** [peer-calls/peer-calls#288]
I created a room from one tab and tried to join as 2nd users in another tab. On both tabs, the connection gets closed with error `Peer connection closed`.

Video: https://www.loom.com/share/c0c34d3e86904c36bc9bdce9afca87ee?sid=b6212117-a9b0-4b4a-b711-98dce4317463

**Comment by prologic** [comment]
How are you running your instance?

**Comment by sujit-baniya** [comment]
first building assets

```js
npm run build
```
then run go server

```go
go run .
```

**Comment by prologic** [comment]
I don't think you can really run this locally very well 🤔

**Comment by jeremija** [comment]
You should be able to debug webrtc connection issues by opening your browser's webrtc tabs:

- `about:webrtc` in Firefox
- `chrome://webrtc-internals` in Chrome

if you're not connected to a local network or a firewall is blocking communication to computers on network (e.g. guest network) then local negotiations won't work since `127.0.0.1` is not used to find other peers.

**Comment by sujit-baniya** [comment]
So, multiple tabs on same browser or different browsers for different participants on same computer (IP with 127.0.0.1) wouldn't work?

**Comment by sujit-baniya** [comment]
I tried it on LAN and still got the same issue on different device

**Comment by jeremija** [comment]
The README.MD in the repo has configuration instructions. I'm not able to provide installation support via GitHub due to the nuances of different WebRTC browser implementations, configuration options, hosting providers and firewall setups. You might also need to run a TURN/STUN server. If you're able to reproduce the issue on peercalls.com I can look into it

**Comment by sujit-baniya** [comment]
How can I run TURN/STUN server locally? I see the issue is related to stun:

```
DOMException: Failed to construct 'RTCPeerConnection': 'stun:global.stun.twilio.com:3478?transport=udp' is not a valid stun or turn URL.
    at new p (http://localhost:3000/static/index.js?v0.0.0:2:466536)
    at http://localhost:3000/static/index.js?v0.0.0:2:632730
    at http://localhost:3000/static/index.js?v0.0.0:2:633426
    at Array.forEach (<anonymous>)
    at i.<anonymous> (http://localhost:3000/static/index.js?v0.0.0:2:632377)
    at i.emit (http://localhost:3000/static/index.js?v0.0.0:2:162396)
```
