### ISSUE TITLE
WebRTC does not match in Microsoft Edge.

### ISSUE THREAD

**Issue by ahmetozalp** [peer-calls/peer-calls#97]
**Describe the bug**
WebRTC does not match in Microsoft Edge.

**Bug Report Checklist**

- [+] I have granted camera/microphone access permissions while testing
- [+] This bug is reproducible on https://peercalls.com

**To Reproduce**
1. Go to peercalls.com
2. Click on 'make room'
3. Open Edge Browser

**Expected behavior*
Both sides see each other in the same way. I see that the other side is in the room but there is no video and no sound.

Edge Information:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

Room Link: https://peercalls.com/call/cf566304-c445-473a-a25c-c9caa247edb6

**Screenshots**

![GitHub Logo](https://i.hizliresim.com/x5qiSJ.png)

** Other Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

**My Mac (please complete the following information):**
 - Device: Macbook Pro 15 Retina i7
 - OS: [Osx Catalina]
 - Browser [Firefox or Chrome]
 - Version [latest]

**Comment by jeremija** [comment]
Thanks for reporting! I don't have a windows computer near me at the moment, but I'd be interested to see the console log when `localStorage.debug` is set to `peercalls,simple-peer`. Would you be able to provide the log?

**Comment by ahmetozalp** [comment]
I do not have a windows computer, but I will tell my friend who conveyed this to me.

**Comment by jeremija** [comment]
Thanks! Also I'd be curious if he can see the video when he joins the same room in two browser windows on the same machine.

It could also be a network issue. Was he able to connect in a different browser on the same computer?

**Comment by ahmetozalp** [comment]
I haven't tried this, but nothing comes in username or something, it just looks like a connected device

**Comment by jeremija** [comment]
I've tried this and it looks like simple-peer doesn't support edge: https://github.com/feross/simple-peer/issues/400

Initiating a connection from Edge to any browser fails because createDataChannel is not defined in `RTCPeerConnection`.

Initiating a connection from Chrome to Edge fails with `destroy (error: [object RTCErrorEvent])` in Chrome

Initiating a connection from Firefox to Edge fails with: `` in Firefox: `destroy (error: OperationError: mid specified for bundle transport in group attribute points at a disabled m-section. (mid=0))`

I'm not exactly sure how to fix this at this point, but it looks like something is different. I've also noticed that at one point the SDP message looked like Plan B, while all the other browsers have switched to Unified Plan.

**Comment by ahmetozalp** [comment]
In fact, I do not work in many browsers, for example, I sometimes live in android device browsers. There are 25 companies testing this now and I receive notification every day.

**Comment by ahmetozalp** [comment]
but this macbook Edge does not have a working solution?

**Comment by jeremija** [comment]
@ahmetozalp Peer Calls works under the latest version of Microsoft Edge, which is based on Chromium. I just tested this:

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/1489493/81837163-c72ab100-9544-11ea-9351-cdef090327ac.png">

Unfortunately, I think it has to be installed manually from the start menu (bottom left corner):

![image](https://user-images.githubusercontent.com/1489493/81837266-ed505100-9544-11ea-9963-b0c731141432.png)

**Comment by ahmetozalp** [comment]
We bought this system for testing. Yes, the versions I marked are working.

<img width="1651" alt="Ekran Resmi 2020-05-13 19 17 57" src="https://user-images.githubusercontent.com/7665820/81838425-c4cd5480-954e-11ea-9e0a-75f549bf6725.png">
